### ISSUE TITLE
Help with Editable Install

### ISSUE THREAD

**Issue by squat** [nix-community/pyproject.nix#114]
I've had a lot of success so far with this library in conjunction with both `buildPythonApplication` and `buildPythonModule`, however I'm a bit stuck on how to get an editable install of a local package with either of these two functions.

My context is that we use a monorepo at work and have a couple of helper CLIs written in Python to aid in various development and SRE tasks. These tools have to stay up-to-date with the rest of the source code otherwise there are no guarantees that anything will work.

I have a pretty basic flake.nix that defines a devShell that installs these CLIs from source in the monorepo using pyproject.nix so that engineers can have a consistent environment, but I can't figure out how to get editable installs working. I've read the some threads on the NixOS Discourse about setting `PYTHONPATH` [0] or how the presence of a `setup.py` should magically make things work [1] but haven't had any luck yet.

Do you have any suggestions? Maybe a (flake-based) venv workflow is more suited for this challenge?

[0] https://discourse.nixos.org/t/nix-shell-buildpythonpackage-pyproject-toml-does-not-seem-to-give-editable-installation-correctly/31180/13
[1] https://discourse.nixos.org/t/installing-a-python-package-in-development-mode-in-nix-shell/18475

**Comment by adisbladis** [comment]
Editable installs works through installing `.pth` files (documented [here](https://docs.python.org/3.8/library/site.html)).
[Poetry2nix has an abstraction for creating such files already](https://github.com/nix-community/poetry2nix/blob/7f304a86324aea2026e65e508c82af7127f9b00d/editable.nix), but I'd like something a bit more flexible than what it currently provides.

I was noodling about what the ideal editable interface looks like a few months ago, but haven't gotten around to revisit it.

> I have a pretty basic flake.nix that defines a devShell that installs these CLIs from source in the monorepo 

Flakes and editable installs play badly, given how Nix copies local paths to the store before evaluation.
This rewrites references from local paths to store paths, making utility of the editable nature questionable.
This can be worked around locally using `--impure`.

**Comment by adisbladis** [comment]
See https://github.com/NixOS/nixpkgs/pull/339228

**Comment by squat** [comment]
Very cool! The apparent simplicity of that PR is definitely misleading. Most of those details go over my head at the moment. Thanks for contributing that!

**Comment by cgahr** [comment]
If your project structure is something like
```
flake.nix
src/
   project/
        ...
pyproject.toml
```
you can use a shellhook in you devShell to point PYTHONPATH to your project like this
```nix
...
pkgs.mkShell {
  packages = ...
  shellHook = ''
    export PYTHONPATH="$(pwd)/src"
  '';
};
```

**Comment by phaer** [comment]
> just works

It works for simple imports, but won't handle entrypoints and so on, so i.e. the scripts mentioned above won't be in PATH after this.

**Comment by adisbladis** [comment]
Closed by https://github.com/nix-community/pyproject.nix/pull/145
