### ISSUE TITLE
Handling psycopg2-binary dependency

### ISSUE THREAD

**Issue by misuzu** [nix-community/pyproject.nix#143]
Suppose I have the [psycopg2-binary](https://pypi.org/project/psycopg2-binary) package in a pyproject.toml, the nixpkgs doesn't have this package so this won't evaluate.
But nixpkgs has the equivalent psycopg2 package.
How do I tell pyproject.nix to use psycopg2 instead of psycopg2-binary without editing the pyproject.toml?
I've tried just making an alias (`psycopg2-binary = psycopg2;`), but it fails to build (`psycopg2-binary not installed`).

**Comment by adisbladis** [comment]
This is nixpkgs python-check-deps hook failing to find psycopg2-binary. The hook is using Python packaging metadata to ensure the environment that is present in the build outputs.

Normally I'd tell you that you need to package a wheel in your Python overlay, but in this instance I think we should fix it in nixpkgs by adding a fake `psycopg2-binary` package that can satisfy the runtime dependency, but still use the `psycopg2` build.

See https://github.com/NixOS/nixpkgs/pull/337621.

**Comment by adisbladis** [comment]
Not an issue in `pyproject.nix` per se. Closing.
