### ISSUE TITLE
How do I use `project.renderers.buildPythonPackage` with dependency groups and extras that don't exist in upstream nixpkgs?

### ISSUE THREAD

**Issue by cpcloud** [nix-community/pyproject.nix#173]
Here's a repo with a failing example:

https://github.com/cpcloud/testpyproj2nix

It looks like when a package doesn't exist upstream, I can't use `buildPythonPackage` to build my local package.

Is there a different way to do this?

**Comment by cpcloud** [comment]
To clarify, I'd like to use the lockfile dependencies produced by uv.

**Comment by adisbladis** [comment]
There is some confusion here :)

`uv2nix` is _not_ using `buildPythonPackage`, or any of the Python packaging code from nixpkgs
Pyproject.nix does support nixpkgs `buildPythonPackage` as one rendering method.
This will use Nixpkgs package definitions as an upstream, and requires that metadata to be in nixpkgs, or an overlay.

I've also implemented a new [build infrastructure](https://nix-community.github.io/pyproject.nix/build.html) which is fixing many of the fundamental issues with the Nixpkgs Python build infra.
This is what `uv2nix` is using.

**Comment by adisbladis** [comment]
Closing this as the reported issue is answered (there is nothing we can do about missing metadata).
